### ISSUE TITLE
cell type: width and height

### ISSUE THREAD

**Issue by Abdulrehmanharisdev** [walkframe/gridsheet#59]
### Description

export declare type CellType<Custom = any> = {
    value?: any;
    style?: React.CSSProperties;
    justifyContent?: React.CSSProperties['justifyContent'];
    alignItems?: React.CSSProperties['alignItems'];
    labeler?: string;
    width?: Width;
    height?: Height;
    renderer?: string;
    parser?: string;
    custom?: Custom;
    prevention?: Prevention;
    changedAt?: Date;
};

   width and height is now woking anymore

**Comment by Abdulrehmanharisdev** [comment]
thnaks it works ....

**Comment by Abdulrehmanharisdev** [comment]
export declare type CellType<Custom = any> = {
value?: any;
style?: React.CSSProperties;
justifyContent?: React.CSSProperties['justifyContent'];
alignItems?: React.CSSProperties['alignItems'];
labeler?: string;
width?: Width;
height?: Height;
renderer?: string;
parser?: string;
custom?: Custom;
prevention?: Prevention;
changedAt?: Date;
};



the problem is when i set the width and height initialy ... it is not automaticly settling ...

**Comment by righ** [comment]
I have confirmed that the following code reflects the initial width and initial height. ([URL](https://github.com/walkframe/gridsheet/blob/master/.storybook/examples/basic/style.stories.tsx))

```js
            A: {},
            B: {
              style: { 
                backgroundColor: "#eeeeee", 
                fontSize: 30, color: "#fff", fontFamily: 'fantasy', letterSpacing: 20, lineHeight: "60px",
              },
              width: 200,
            },
            C: {
              style: { backgroundColor: "#dddddd" },
            },
            D: {
              style: { backgroundColor: "#cccccc" },
            },
            E: {
              style: { backgroundColor: "#bbbbbb" },
            },
            1: {
              style: { color: "#333" },
            },
            2: {
              style: { color: "#F00" },
              height: 100,
              alignItems: 'center',
              justifyContent: 'center',
            },
            3: {
              style: { color: "#0C0" },
              height: 250,
            },
```


Please let me know the code how you have set it up.

**Comment by Abdulrehmanharisdev** [comment]
export const convertToInitialCells = (
  content: string[][],
  formatting: CellFormatting[][]
) => {
  const cells: { [key: string]: any } = {};

  for (let row = 0; row < content.length; row++) {
    for (let col = 0; col < content[row].length; col++) {
      const cellValue = content[row][col];

      const defaultStyle = {
        backgroundColor: "D3D3D3",
        textColor: "000000",
        textAlign: "left",
        fontSize: "12",
        editorColumnWidth: 45,
        editorRowHeight: 20,
        borderColor: "000000",
        textDecoration: "normal",
        fontWeight: "normal",
        fontStyle: "normal",
      };

      const cellStyle = (formatting[row] && formatting[row][col]?.style) || defaultStyle;

      const cellKey = String.fromCharCode(65 + col) + (row + 1); // Generates cell key like A1, B1, etc.

      cells[cellKey] = {
        value: cellValue,
        width: 400, // dynamic values 
        height: 3000, // dynamic values
        justifyContent: getAlignment(cellStyle.textAlign),
        style: {
          color: `#${cellStyle.textColor}`,
          backgroundColor: `#${cellStyle.backgroundColor}`,
          fontSize: `${cellStyle.fontSize}pt`,
          border: `1px solid #${cellStyle.borderColor}`,
          overflow: "hidden",
          whiteSpace: "normal",
          fontFamily: cellStyle.font,
          fontWeight: "bold",
          fontStyle: "italic",
          textDecoration: "underline",
        },
      };
    }
  }

  return constructInitialCells({ cells });
};

**Comment by Abdulrehmanharisdev** [comment]
so the above approch doesnot work for me so i created a custom function to set the row height and column width even ever the page loads

**Comment by righ** [comment]
When changing the width of B, you should specify `B`, not in the form `B{number}` as in `B1`.
Looking at the code you presented, `String.fromCharCode(65 + col) + (row + 1)`, it seems to me that this would include the number after B. Try using p2a, a utility function provided by gridsheet. To specify column B, use `p2a({ x: 2, y: 0 })`.
If this does not solve the problem, please provide the actual code for the part of the code to be applied.

**Comment by Abdulrehmanharisdev** [comment]
@righ , Thank you for all of your help.
