### ISSUE TITLE
[BUG] - underline  Not Applied in View Mode 

### ISSUE THREAD

**Issue by Abdulrehmanharisdev** [walkframe/gridsheet#60]
### Description

[BUG] - bold , italic , underline  Not Applied in View Mode but only on editor mode

**Comment by righ** [comment]
There was still a bug with text-decoration not working, fixed in [v1.0.8.](https://www.npmjs.com/package/@gridsheet/react-core/v/1.0.8)

As for bold , italic, I have confirmed that it works effectively in the version before the fix.
Perhaps there was a mistake in the configuration you wrote. the following code works fine in v1.0.8. (It also works in v1.0.7 and earlier, except for the UNDERLINE)

```js
  {
    "A5": {
      "value": "test", 
      "style": {"fontWeight": "bold", "fontStyle": "italic", "textDecoration": "underline"}
    }
  }
```

**Comment by Abdulrehmanharisdev** [comment]
![image](https://github.com/user-attachments/assets/2d9ce962-94e5-47d0-9428-c5834e88704a)
 yes under is only working in editing mode

**Comment by Abdulrehmanharisdev** [comment]
Hi @righ,

After updating the package, I encountered an issue where previously functioning formatting properties (such as fontStyle, fontWeight, textDecoration, alignmnet , fontsize , coloring etc.) are now throwing errors when attempting to modify them. The specific error is:
```
Cannot assign to read only property 'fontStyle' of object '#<Object>'
TypeError: Cannot assign to read only property 'fontStyle' of object '#<Object>'
```


const updateCellFormatting = (
    tableRef: TableRef,
    rowIndex: number,
    colIndex: number,
    newAlignment: {
      alignItems?: string;
      justifyContent?: string;
    },
    decorators: {
      fontWeight?: string;
      fontStyle?: string;
      textDecoration?: string;
    },
    newBackgroundColor: string,
    newTextColor: string,
    fontSize?: string
  ) => {
    try {
      if (!tableRef) throw new Error("tableRef is undefined or null.");

      const { dispatch, table } = tableRef;
      if (!table) throw new Error("Table data is missing in tableRef.");

      const { idMatrix, addressesById } = table as any;
      if (!idMatrix || !addressesById)
        throw new Error("Table data is incomplete or malformed.");

      const cellId = idMatrix[rowIndex - 1]?.[colIndex - 1];
      if (!cellId)
        throw new Error(
          `Cell ID not found for row: ${rowIndex}, col: ${colIndex}.`
        );

      const cell = table.getById(cellId);
      const address = addressesById[cellId];
      if (!cell) throw new Error(`Cell not found for ID: ${cellId}.`);

      // Apply formatting changes
      if (newAlignment.justifyContent !== undefined) {
        cell.justifyContent = newAlignment.justifyContent;
      }
      if (fontSize !== undefined && fontSize !== "") {
        cell.style!.fontSize = `${fontSize}pt`;
      }
      if (decorators.fontStyle !== undefined) {
        cell.style!.fontStyle = decorators.fontStyle;
      }
      if (decorators.fontWeight !== undefined) {
        cell.style!.fontWeight = decorators.fontWeight;
      }
      if (decorators.textDecoration !== undefined) {
        cell.style!.textDecoration = decorators.textDecoration;
      }
      if (newBackgroundColor !== "") {
        cell.style!.backgroundColor = newBackgroundColor;
      }
      if (newTextColor !== "") {
        cell.style!.color = newTextColor;
      }

      // Dispatch the updated cell
      dispatch(
        table.update({
          diff: { [address]: cell }
        })
      );
    } catch (error) {
      console.error("Error updating cell formatting:", error);
    }
  };
```

**Comment by Abdulrehmanharisdev** [comment]
thank after the new update its working fine now
