### ISSUE TITLE
💡 [REQUEST] Unable to drag and select multiple cells   

### ISSUE THREAD

**Issue by Abdulrehmanharisdev** [walkframe/gridsheet#61]
### Description

while applying a formula i am unable to drag and select multiple cells .. 
i have to manully write the each cell addresss 
![image](https://github.com/user-attachments/assets/dbd85416-0fef-4498-b2f1-d1072320b3cb)

**Comment by righ** [comment]
Address input by selection is not yet supported.
Please look forward to future development.
I will change the title as it is not a bug.

**Comment by Abdulrehmanharisdev** [comment]
@righ  thanks for adding this functionality

**Comment by righ** [comment]
I recommend using the latest version since bugs and other issues have been fixed.
