### ISSUE TITLE
🐛 [BUG] -Editor width issue 

### ISSUE THREAD

**Issue by Abdulrehmanharisdev** [walkframe/gridsheet#62]
### Description

When a cell is already selected, changing the width of the column does not immediately update the editor's column width. The new width only takes effect after selecting another cell and then reselecting the original cell.

### Screenshots

![image](https://github.com/user-attachments/assets/186c9e62-ac19-4da2-91b3-5dd9fff9bce3)

### Browsers

Chrome

### OS

Windows

**Comment by righ** [comment]
Thanks for reporting the bug.
Please check back as we have fixed it in v1.0.9.

**Comment by Abdulrehmanharisdev** [comment]
thanks
