### ISSUE TITLE
Bug: The formula bar is not functioning properly. It requires pressing a key 3-4 times to input a single character.

### ISSUE THREAD

**Issue by Abdulrehmanharisdev** [walkframe/gridsheet#65]
![image](https://github.com/user-attachments/assets/5f7b27e8-356e-41c8-a0cb-dc19fc330a89)

**Comment by Abdulrehmanharisdev** [comment]
@righ , can you look into this?

**Comment by righ** [comment]
Thank you for your report.
However, I could not reproduce it on my mac (chrome, firefox, safari).
Could you please describe the detailed reproduction conditions? If it's too hard, getting a screencast might help me solve the problem.
Also, please mention what OS and browser you are using.

**Comment by righ** [comment]
Perhaps you are using 1.1.0-alpha.0?
I think using 1.1.0-alpha.1 will solve the problem.
